/* Literal instruction oracle and static multiply controls. */
__asm__(".text\n"
        ".macro START name\n"
        ".p2align 4\n"
#ifdef __APPLE__
        ".globl _\\name\n"
        "_\\name:\n"
        ".set \\name, _\\name\n"
#else
        ".globl \\name\n"
        "\\name:\n"
#endif
        ".endm\n"
        ".macro RESULT condition\n"
        "\\condition %al\n"
        "movzbl %al, %eax\n"
        "ret\n"
        ".endm\n"
        ".macro INPUT\n"
#ifdef __i386__
        "movl 4(%esp), %ecx\n"
#else
        "movl %edi, %ecx\n"
#endif
        ".endm\n"
        ".macro CELL\n"
#ifdef __i386__
        "movl $mp_cell, %ecx\n"
#else
        "leaq mp_cell(%rip), %rcx\n"
#endif
        ".endm\n"
        "START mp_execute\n"
#ifdef __i386__
        "pushl %ebx\n"
        "pushl %esi\n"
        "pushl %edi\n"
        "pushl %ebp\n"
        "movl 20(%esp), %eax\n"
        "movl 28(%esp), %ecx\n"
        "movl 36(%esp), %ebp\n"
        "movl 40(%esp), %edi\n"
        "movl 44(%esp), %ebx\n"
        "movl 48(%esp), %esi\n"
        "movl $0xa5a55a5a, %edx\n"
        "cmpl $8, %edi\n"
        "je 1f\n"
        "cmpl $16, %edi\n"
        "je 2f\n"
        "jmp 3f\n"
#else
        "movl %edx, %r10d\n"
        "movl %ecx, %r11d\n"
        "movq %rdi, %rax\n"
        "movq %rsi, %rcx\n"
        "movabsq $0x12345678a5a55a5a, %rdx\n"
        "cmpl $8, %r11d\n"
        "je 1f\n"
        "cmpl $16, %r11d\n"
        "je 2f\n"
        "cmpl $32, %r11d\n"
        "je 3f\n"
        "jmp 4f\n"
#endif
        ".macro EXEC text:vararg\n"
#ifdef __i386__
        "pushl %ebx\n"
        "popfl\n"
        "pushfl\n"
        "popl %edi\n"
        "\\text\n"
        "pushfl\n"
        "popl %ebx\n"
        "movl %eax, 0(%esi)\n"
        "movl %edx, 4(%esi)\n"
        "movl %edi, 8(%esi)\n"
        "movl %ebx, 12(%esi)\n"
        "popl %ebp\n"
        "popl %edi\n"
        "popl %esi\n"
        "popl %ebx\n"
#else
        "pushq %r8\n"
        "popfq\n"
        "pushfq\n"
        "popq %rdi\n"
        "\\text\n"
        "pushfq\n"
        "popq %rsi\n"
        "movq %rax, 0(%r9)\n"
        "movq %rdx, 8(%r9)\n"
        "movq %rdi, 16(%r9)\n"
        "movq %rsi, 24(%r9)\n"
#endif
        "ret\n"
        ".endm\n"
        ".macro FORM value\n"
#ifdef __i386__
        "cmpl $\\value, %ebp\n"
#else
        "cmpl $\\value, %r10d\n"
#endif
        ".endm\n"
        ".macro DISPATCH suffix, source, dest, immediate\n"
        "FORM 0\n"
        "je 5f\n"
        "FORM 1\n"
        "je 6f\n"
        "FORM 2\n"
        "je 7f\n"
        "FORM 3\n"
        "je 8f\n"
        "EXEC imul\\suffix $\\immediate, \\source, \\dest\n"
        "5: EXEC mul\\suffix \\source\n"
        "6: EXEC imul\\suffix \\source\n"
        "7: EXEC imul\\suffix \\source, \\dest\n"
        "8: EXEC imul\\suffix $-7, \\source, \\dest\n"
        ".endm\n"
        "1: FORM 0\n"
        "je 5f\n"
        "EXEC imulb %cl\n"
        "5: EXEC mulb %cl\n"
        "2: DISPATCH w, %cx, %ax, -32768\n"
        "3: DISPATCH l, %ecx, %eax, -2147483648\n"
#ifndef __i386__
        "4: DISPATCH q, %rcx, %rax, -2147483648\n"
#endif
        "START mp_mul_byte_value\n"
        "movl $200, %eax\n"
        "movl $2, %ecx\n"
        "mulb %cl\n"
        "cmpw $400, %ax\n"
        "RESULT sete\n"
        "START mp_mul_byte_cf\n"
        "movl $200, %eax\n"
        "movl $2, %ecx\n"
        "mulb %cl\n"
        "RESULT setb\n"
        "START mp_imul_byte_value\n"
        "movl $128, %eax\n"
        "movl $2, %ecx\n"
        "imulb %cl\n"
        "cmpw $0xff00, %ax\n"
        "RESULT sete\n"
        "START mp_imul_byte_of\n"
        "movl $128, %eax\n"
        "movl $255, %ecx\n"
        "imulb %cl\n"
        "RESULT seto\n"
        "START mp_mul_word_high\n"
        "movl $65535, %eax\n"
        "movl $65535, %ecx\n"
        "mulw %cx\n"
        "cmpw $65534, %dx\n"
        "RESULT sete\n"
        "START mp_word_slices\n"
        "movl $0x1234ffff, %eax\n"
        "movl $0x55660000, %edx\n"
        "movl $65535, %ecx\n"
        "mulw %cx\n"
        "cmpl $0x5566fffe, %edx\n"
        "RESULT sete\n"
        "START mp_word_low_slice\n"
        "movl $0x1234ffff, %eax\n"
        "movl $65535, %ecx\n"
        "mulw %cx\n"
        "cmpl $0x12340001, %eax\n"
        "RESULT sete\n"
        "START mp_imul_word_two\n"
        "movl $0x12348000, %eax\n"
        "movl $2, %ecx\n"
        "imulw %cx, %ax\n"
        "cmpl $0x12340000, %eax\n"
        "RESULT sete\n"
        "START mp_imul_word_imm8\n"
        "movl $0x12340000, %eax\n"
        "movl $5, %ecx\n"
        "imulw $-7, %cx, %ax\n"
        "cmpl $0x1234ffdd, %eax\n"
        "RESULT sete\n"
        "START mp_imul_word_imm16\n"
        "movl $2, %ecx\n"
        "imulw $-32768, %cx, %ax\n"
        "RESULT seto\n"
        "START mp_imul_word_high\n"
        "movl $65535, %eax\n"
        "movl $2, %ecx\n"
        "imulw %cx\n"
        "cmpw $65535, %dx\n"
        "RESULT sete\n"
        "START mp_mul_dword_high\n"
        "movl $-1, %eax\n"
        "movl $-1, %ecx\n"
        "mull %ecx\n"
        "cmpl $-2, %edx\n"
        "RESULT sete\n"
        "START mp_imul_dword_high\n"
        "movl $-1, %eax\n"
        "movl $2, %ecx\n"
        "imull %ecx\n"
        "cmpl $-1, %edx\n"
        "RESULT sete\n"
        "START mp_imul_fits\n"
        "movl $-1, %eax\n"
        "movl $2, %ecx\n"
        "imull %ecx\n"
        "RESULT setno\n"
        "START mp_imul_two\n"
        "movl $0x80000000, %eax\n"
        "movl $2, %ecx\n"
        "imull %ecx, %eax\n"
        "RESULT seto\n"
        "START mp_imul_imm8\n"
        "movl $5, %ecx\n"
        "imull $-7, %ecx, %eax\n"
        "cmpl $-35, %eax\n"
        "RESULT sete\n"
        "START mp_imul_imm32\n"
        "movl $2, %ecx\n"
        "imull $-2147483648, %ecx, %eax\n"
        "RESULT seto\n"
        "START mp_unknown_zero\n"
        "INPUT\n"
        "movl $0, %eax\n"
        "mull %ecx\n"
        "RESULT setnb\n"
        "START mp_unknown_one_cf\n"
        "INPUT\n"
        "movl $1, %eax\n"
        "mull %ecx\n"
        "RESULT setnb\n"
        "START mp_unknown_one_high\n"
        "INPUT\n"
        "movl $1, %eax\n"
        "mull %ecx\n"
        "cmpl $0, %edx\n"
        "RESULT sete\n"
        "START mp_signed_unknown_one\n"
        "INPUT\n"
        "movl $1, %eax\n"
        "imull %ecx\n"
        "RESULT setno\n"
        "START mp_high_source\n"
        "movl $3, %eax\n"
        "movl $7, %edx\n"
        "mull %edx\n"
        "cmpl $21, %eax\n"
        "RESULT sete\n"
        "START mp_accumulator_source\n"
        "movl $3, %eax\n"
        "imull %eax\n"
        "cmpl $9, %eax\n"
        "RESULT sete\n"
        "START mp_high_byte_source\n"
        "movl $0x12340203, %eax\n"
        "mulb %ah\n"
        "cmpl $0x12340006, %eax\n"
        "RESULT sete\n"
        "START mp_imul_aliased_immediate\n"
        "movl $5, %eax\n"
        "imull $-7, %eax, %eax\n"
        "cmpl $-35, %eax\n"
        "RESULT sete\n"
        "START mp_memory\n"
        "CELL\n"
#ifdef __i386__
        "movl $3, (%ecx)\n"
        "movl $7, %eax\n"
        "mull (%ecx)\n"
#else
        "movl $3, (%rcx)\n"
        "movl $7, %eax\n"
        "mull (%rcx)\n"
#endif
        "cmpl $21, %eax\n"
        "RESULT sete\n"
        "START mp_memory_signed\n"
        "CELL\n"
#ifdef __i386__
        "movl $-3, (%ecx)\n"
        "movl $7, %eax\n"
        "imull (%ecx)\n"
#else
        "movl $-3, (%rcx)\n"
        "movl $7, %eax\n"
        "imull (%rcx)\n"
#endif
        "cmpl $-21, %eax\n"
        "RESULT sete\n"
        "START mp_memory_two\n"
        "CELL\n"
#ifdef __i386__
        "movl $-3, (%ecx)\n"
        "movl $7, %eax\n"
        "imull (%ecx), %eax\n"
#else
        "movl $-3, (%rcx)\n"
        "movl $7, %eax\n"
        "imull (%rcx), %eax\n"
#endif
        "cmpl $-21, %eax\n"
        "RESULT sete\n"
        "START mp_memory_three\n"
        "CELL\n"
#ifdef __i386__
        "movl $-3, (%ecx)\n"
        "movl $7, %eax\n"
        "imull $-7, (%ecx), %eax\n"
#else
        "movl $-3, (%rcx)\n"
        "movl $7, %eax\n"
        "imull $-7, (%rcx), %eax\n"
#endif
        "cmpl $21, %eax\n"
        "RESULT sete\n"
        "START mp_memory_retained\n"
        "CELL\n"
#ifdef __i386__
        "movl $7, (%ecx)\n"
        "movl $7, %eax\n"
        "mull (%ecx)\n"
        "movl (%ecx), %eax\n"
#else
        "movl $7, (%rcx)\n"
        "movl $7, %eax\n"
        "mull (%rcx)\n"
        "movl (%rcx), %eax\n"
#endif
        "cmpl $7, %eax\n"
        "RESULT sete\n"
#ifndef __i386__
        "START mp_mul_quad_high\n"
        "movq $-1, %rax\n"
        "movq $-1, %rcx\n"
        "mulq %rcx\n"
        "cmpq $-2, %rdx\n"
        "RESULT sete\n"
        "START mp_imul_quad_high\n"
        "movabsq $0x8000000000000000, %rax\n"
        "movq $2, %rcx\n"
        "imulq %rcx\n"
        "cmpq $-1, %rdx\n"
        "RESULT sete\n"
        "START mp_quad_imm32\n"
        "movq $-1, %rcx\n"
        "imulq $-2147483648, %rcx, %rax\n"
        "movl $0x80000000, %edx\n"
        "cmpq %rdx, %rax\n"
        "RESULT sete\n"
        "START mp_zero_upper_low\n"
        "movq $-1, %rax\n"
        "movl $2, %ecx\n"
        "mull %ecx\n"
        "movl $0xfffffffe, %edi\n"
        "cmpq %rdi, %rax\n"
        "RESULT sete\n"
        "START mp_zero_upper_high\n"
        "movq $-1, %rdx\n"
        "movl $3, %eax\n"
        "movl $7, %ecx\n"
        "mull %ecx\n"
        "cmpq $0, %rdx\n"
        "RESULT sete\n"
        "START mp_quad_two\n"
        "movq $-1, %rax\n"
        "movq $2, %rcx\n"
        "imulq %rcx, %rax\n"
        "cmpq $-2, %rax\n"
        "RESULT sete\n"
        "START mp_quad_imm8\n"
        "movq $5, %rcx\n"
        "imulq $-7, %rcx, %rax\n"
        "cmpq $-35, %rax\n"
        "RESULT sete\n"
        "START mp_quad_full_extended\n"
        "movq $3, %rax\n"
        "movq $7, %r8\n"
        "mulq %r8\n"
        "cmpq $21, %rax\n"
        "RESULT sete\n"
        "START mp_extended\n"
        "movl $-3, %r8d\n"
        "movl $7, %r9d\n"
        "imull %r8d, %r9d\n"
        "cmpl $-21, %r9d\n"
        "RESULT sete\n"
#endif
        "START mp_undefined_zf\n"
        "xorl %eax, %eax\n"
        "movl $1, %ecx\n"
        "mull %ecx\n"
        "RESULT sete\n"
        "START mp_undefined_sf\n"
        "xorl %eax, %eax\n"
        "movl $1, %ecx\n"
        "mull %ecx\n"
        "RESULT sets\n"
        "START mp_undefined_pf\n"
        "xorl %eax, %eax\n"
        "movl $1, %ecx\n"
        "imull %ecx, %eax\n"
        "RESULT setp\n"
        "START mp_unknown_multiply\n"
        "INPUT\n"
        "movl $3, %eax\n"
        "mull %ecx\n"
        "RESULT setb\n"
        "START mp_memory_initial\n"
        "CELL\n"
        "movl $3, %eax\n"
#ifdef __i386__
        "mull (%ecx)\n"
#else
        "mull (%rcx)\n"
#endif
        "RESULT setb\n"
        "START mp_locked\n"
        "movl $3, %eax\n"
        "movl $7, %ecx\n"
        ".byte 0xf0, 0xf7, 0xe1\n"
        "RESULT setb\n"
        "START mp_address_prefix\n"
        "movl $3, %eax\n"
        "movl $7, %ecx\n"
        ".byte 0x67, 0xf7, 0xe1\n"
        "cmpl $21, %eax\n"
        "RESULT sete\n"
        "START mp_segment_prefix\n"
        "movl $3, %eax\n"
        "movl $7, %ecx\n"
        ".byte 0x64, 0xf7, 0xe9\n"
        "cmpl $21, %eax\n"
        "RESULT sete\n"
        "START mp_stack_source\n"
        "movl $3, %eax\n"
#ifdef __i386__
        "pushl $7\n"
        "mull (%esp)\n"
        "popl %ecx\n"
        "cmpl $21, %eax\n"
#else
        "pushq $7\n"
        "mulq (%rsp)\n"
        "popq %rcx\n"
        "cmpq $21, %rax\n"
#endif
        "RESULT sete\n"
        "START mp_target\n"
#ifdef __i386__
        "movl $mp_destination, %ecx\n"
#else
        "leaq mp_destination(%rip), %rcx\n"
#endif
        "movl $3, %eax\n"
        "movl $7, %edx\n"
        "mull %edx\n"
#ifdef __i386__
        "pushl %ecx\n"
#else
        "pushq %rcx\n"
#endif
        "ret\n"
        "START mp_destination\n"
        "movl $7, %eax\n"
        "ret\n"
        ".data\n"
        ".p2align 3\n"
        "START mp_cell\n"
        ".quad 7\n");
