/* Universal compound conditions and conflicting/overflow controls. */
__asm__(
    ".text\n"
    ".macro START name\n"
    ".p2align 4\n"
#ifdef __APPLE__
    ".globl _\\name\n"
    "_\\name:\n"
    ".set \\name, _\\name\n"
#else
    ".globl \\name\n"
    "\\name:\n"
#endif
    ".endm\n"
    ".macro ADDRESS name, reg\n"
#ifdef __i386__
    "movl $\\name, %e\\reg\n"
#else
    "leaq \\name(%rip), %r\\reg\n"
#endif
    ".endm\n"
    ".macro FLAGS profile\n"
#ifdef __i386__
    "pushl $((\\profile & 1) | ((\\profile & 2)<<1) | ((\\profile & 4)<<2) | ((\\profile & 8)<<3) | ((\\profile & 16)<<3) | ((\\profile & 32)<<6) | 2)\n"
    "popfl\n"
#else
    "pushq $((\\profile & 1) | ((\\profile & 2)<<1) | ((\\profile & 4)<<2) | ((\\profile & 8)<<3) | ((\\profile & 16)<<3) | ((\\profile & 32)<<6) | 2)\n"
    "popfq\n"
#endif
    ".endm\n"
    ".macro REL name, cc, first, second, kind\n"
    "START \\name\n"
#ifdef __i386__
    "movl 4(%esp), %edx\n"
#else
    "movl %edi, %edx\n"
#endif
    "testl %edx, %edx\n jz 1f\n"
    "FLAGS \\first\n jmp 2f\n"
    "1: FLAGS \\second\n"
    "2:\n"
    ".if \\kind == 0\n"
    "j\\cc 3f\n movl $8, %eax\n ret\n"
    "3: movl $7, %eax\n ret\n"
    ".elseif \\kind == 1\n"
    "movl $0x123400, %eax\n set\\cc %al\n ret\n"
    ".elseif \\kind == 2\n"
    "movl $8, %eax\n movl $7, %ecx\n cmov\\cc %ecx, %eax\n ret\n"
    ".else\n ADDRESS rc_cell, dx\n"
#ifdef __i386__
    "movl $7, (%edx)\n movl $8, %eax\n cmov\\cc (%edx), %eax\n ret\n"
#else
    "movl $7, (%rdx)\n movl $8, %eax\n cmov\\cc (%rdx), %eax\n ret\n"
#endif
    ".endif\n .endm\n"
    "REL rc_be_true_branch, be, 1, 8, 0\n"
    "REL rc_be_true_branch_dynamic, be, 1, 0, 0\n"
    "REL rc_be_true_set, be, 1, 8, 1\n"
    "REL rc_be_true_set_dynamic, be, 1, 0, 1\n"
    "REL rc_be_true_move, be, 1, 8, 2\n"
    "REL rc_be_true_move_dynamic, be, 1, 0, 2\n"
    "REL rc_be_true_memory, be, 1, 8, 3\n"
    "REL rc_be_true_memory_dynamic, be, 1, 0, 3\n"
    "REL rc_a_false_branch, a, 1, 8, 0\n"
    "REL rc_a_false_branch_dynamic, a, 1, 0, 0\n"
    "REL rc_a_false_set, a, 1, 8, 1\n"
    "REL rc_a_false_set_dynamic, a, 1, 0, 1\n"
    "REL rc_a_false_move, a, 1, 8, 2\n"
    "REL rc_a_false_move_dynamic, a, 1, 0, 2\n"
    "REL rc_a_false_memory, a, 1, 8, 3\n"
    "REL rc_a_false_memory_dynamic, a, 1, 0, 3\n"
    "REL rc_l_true_branch, l, 16, 32, 0\n"
    "REL rc_l_true_branch_dynamic, l, 16, 0, 0\n"
    "REL rc_l_true_set, l, 16, 32, 1\n"
    "REL rc_l_true_set_dynamic, l, 16, 0, 1\n"
    "REL rc_l_true_move, l, 16, 32, 2\n"
    "REL rc_l_true_move_dynamic, l, 16, 0, 2\n"
    "REL rc_l_true_memory, l, 16, 32, 3\n"
    "REL rc_l_true_memory_dynamic, l, 16, 0, 3\n"
    "REL rc_l_false_branch, l, 0, 48, 0\n"
    "REL rc_l_false_branch_dynamic, l, 0, 16, 0\n"
    "REL rc_l_false_set, l, 0, 48, 1\n"
    "REL rc_l_false_set_dynamic, l, 0, 16, 1\n"
    "REL rc_l_false_move, l, 0, 48, 2\n"
    "REL rc_l_false_move_dynamic, l, 0, 16, 2\n"
    "REL rc_l_false_memory, l, 0, 48, 3\n"
    "REL rc_l_false_memory_dynamic, l, 0, 16, 3\n"
    "REL rc_ge_true_branch, ge, 0, 48, 0\n"
    "REL rc_ge_true_branch_dynamic, ge, 0, 16, 0\n"
    "REL rc_ge_true_set, ge, 0, 48, 1\n"
    "REL rc_ge_true_set_dynamic, ge, 0, 16, 1\n"
    "REL rc_ge_true_move, ge, 0, 48, 2\n"
    "REL rc_ge_true_move_dynamic, ge, 0, 16, 2\n"
    "REL rc_ge_true_memory, ge, 0, 48, 3\n"
    "REL rc_ge_true_memory_dynamic, ge, 0, 16, 3\n"
    "REL rc_ge_false_branch, ge, 16, 32, 0\n"
    "REL rc_ge_false_branch_dynamic, ge, 16, 0, 0\n"
    "REL rc_ge_false_set, ge, 16, 32, 1\n"
    "REL rc_ge_false_set_dynamic, ge, 16, 0, 1\n"
    "REL rc_ge_false_move, ge, 16, 32, 2\n"
    "REL rc_ge_false_move_dynamic, ge, 16, 0, 2\n"
    "REL rc_ge_false_memory, ge, 16, 32, 3\n"
    "REL rc_ge_false_memory_dynamic, ge, 16, 0, 3\n"
    "REL rc_le_true_branch, le, 16, 32, 0\n"
    "REL rc_le_true_branch_dynamic, le, 16, 0, 0\n"
    "REL rc_le_true_set, le, 16, 32, 1\n"
    "REL rc_le_true_set_dynamic, le, 16, 0, 1\n"
    "REL rc_le_true_move, le, 16, 32, 2\n"
    "REL rc_le_true_move_dynamic, le, 16, 0, 2\n"
    "REL rc_le_true_memory, le, 16, 32, 3\n"
    "REL rc_le_true_memory_dynamic, le, 16, 0, 3\n"
    "REL rc_le_false_branch, le, 0, 48, 0\n"
    "REL rc_le_false_branch_dynamic, le, 0, 16, 0\n"
    "REL rc_le_false_set, le, 0, 48, 1\n"
    "REL rc_le_false_set_dynamic, le, 0, 16, 1\n"
    "REL rc_le_false_move, le, 0, 48, 2\n"
    "REL rc_le_false_move_dynamic, le, 0, 16, 2\n"
    "REL rc_le_false_memory, le, 0, 48, 3\n"
    "REL rc_le_false_memory_dynamic, le, 0, 16, 3\n"
    "REL rc_g_true_branch, g, 0, 48, 0\n"
    "REL rc_g_true_branch_dynamic, g, 0, 16, 0\n"
    "REL rc_g_true_set, g, 0, 48, 1\n"
    "REL rc_g_true_set_dynamic, g, 0, 16, 1\n"
    "REL rc_g_true_move, g, 0, 48, 2\n"
    "REL rc_g_true_move_dynamic, g, 0, 16, 2\n"
    "REL rc_g_true_memory, g, 0, 48, 3\n"
    "REL rc_g_true_memory_dynamic, g, 0, 16, 3\n"
    "REL rc_g_false_branch, g, 16, 32, 0\n"
    "REL rc_g_false_branch_dynamic, g, 16, 0, 0\n"
    "REL rc_g_false_set, g, 16, 32, 1\n"
    "REL rc_g_false_set_dynamic, g, 16, 0, 1\n"
    "REL rc_g_false_move, g, 16, 32, 2\n"
    "REL rc_g_false_move_dynamic, g, 16, 0, 2\n"
    "REL rc_g_false_memory, g, 16, 32, 3\n"
    "REL rc_g_false_memory_dynamic, g, 16, 0, 3\n"
    "START rc_cap\n"
#ifdef __i386__
    "movl 4(%esp), %edx\n"
#else
    "movl %edi, %edx\n"
#endif
    "cmpl $0, %edx\n je .Lrc_arm0\n"
    "cmpl $1, %edx\n je .Lrc_arm1\n"
    "cmpl $2, %edx\n je .Lrc_arm2\n"
    "cmpl $3, %edx\n je .Lrc_arm3\n"
    "cmpl $4, %edx\n je .Lrc_arm4\n"
    "cmpl $5, %edx\n je .Lrc_arm5\n"
    "cmpl $6, %edx\n je .Lrc_arm6\n"
    "cmpl $7, %edx\n je .Lrc_arm7\n"
    "jmp .Lrc_arm8\n"
    ".Lrc_arm0: FLAGS 1\n movl $0, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm1: FLAGS 8\n movl $1, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm2: FLAGS 1\n movl $2, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm3: FLAGS 8\n movl $3, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm4: FLAGS 1\n movl $4, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm5: FLAGS 8\n movl $5, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm6: FLAGS 1\n movl $6, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm7: FLAGS 8\n movl $7, %ecx\n jmp .Lrc_join\n"
    ".Lrc_arm8: FLAGS 1\n movl $8, %ecx\n jmp .Lrc_join\n"
    ".Lrc_join: movl $0x123400, %eax\n setbe %al\n ret\n"
    "START rc_lock_branch\n FLAGS 1\n .byte 0xf0\n jbe 3f\n"
    "movl $8, %eax\n ret\n 3: movl $7, %eax\n ret\n"
    "START rc_lock_set\n FLAGS 1\n movl $0x123400, %eax\n .byte 0xf0\n setbe %al\n ret\n"
    "START rc_lock_move\n FLAGS 1\n movl $8, %eax\n movl $7, %ecx\n .byte 0xf0\n cmovbe %ecx, %eax\n ret\n"
    "START rc_lock_memory\n FLAGS 1\n ADDRESS rc_cell, dx\n"
#ifdef __i386__
    "movl $7, (%edx)\n movl $8, %eax\n .byte 0xf0\n cmovbe (%edx), %eax\n ret\n"
#else
    "movl $7, (%rdx)\n movl $8, %eax\n .byte 0xf0\n cmovbe (%rdx), %eax\n ret\n"
#endif
    "START rc_end\n ret\n"
    ".data\n .p2align 3\n rc_cell: .quad 0\n"
#ifndef __APPLE__
    ".section .note.GNU-stack,\"\",@progbits\n"
#endif
);
