/* Native instruction oracle and static fixtures, emitted as literal GNU assembly. */
__asm__(".text\n"
        ".macro START name\n"
        ".p2align 4\n"
#ifdef __APPLE__
        ".globl _\\name\n"
        "_\\name:\n"
        ".set \\name, _\\name\n"
#else
        ".globl \\name\n"
        "\\name:\n"
#endif
        ".endm\n"
        ".macro RESULT condition\n"
        "    \\condition %al\n"
        "    movzbl %al, %eax\n"
        "    ret\n"
        ".endm\n"
        ".macro INPUT\n"
#ifdef __i386__
        "    movl 4(%esp), %ecx\n"
#else
        "    movl %edi, %ecx\n"
#endif
        ".endm\n"
        "START rt_execute\n"
#ifdef __i386__
        "    pushl %ebx\n"
        "    pushl %esi\n"
        "    pushl %edi\n"
        "    movl 16(%esp), %eax\n"
        "    movl 24(%esp), %ecx\n"
        "    movl 28(%esp), %edx\n"
        "    movl 32(%esp), %edi\n"
        "    movl 36(%esp), %ebx\n"
        "    movl 40(%esp), %esi\n"
        "    cmpl $8, %edi\n"
        "    je 1f\n"
        "    cmpl $16, %edi\n"
        "    je 2f\n"
        "    jmp 3f\n"
#else
        "    movl %ecx, %r10d\n"
        "    movl %esi, %ecx\n"
        "    movq %rdi, %rax\n"
        "    cmpl $8, %r10d\n"
        "    je 1f\n"
        "    cmpl $16, %r10d\n"
        "    je 2f\n"
        "    cmpl $32, %r10d\n"
        "    je 3f\n"
        "    jmp 4f\n"
#endif
        ".macro EXEC instruction, reg\n"
#ifdef __i386__
        "    pushl %ebx\n"
        "    popfl\n"
        "    pushfl\n"
        "    popl %edi\n"
        "    \\instruction %cl, \\reg\n"
        "    pushfl\n"
        "    popl %ebx\n"
        "    movl %eax, 0(%esi)\n"
        "    movl %edi, 4(%esi)\n"
        "    movl %ebx, 8(%esi)\n"
        "    popl %edi\n"
        "    popl %esi\n"
        "    popl %ebx\n"
#else
        "    pushq %r8\n"
        "    popfq\n"
        "    pushfq\n"
        "    popq %rdi\n"
        "    \\instruction %cl, \\reg\n"
        "    pushfq\n"
        "    popq %rsi\n"
        "    movq %rax, 0(%r9)\n"
        "    movq %rdi, 8(%r9)\n"
        "    movq %rsi, 16(%r9)\n"
#endif
        "    ret\n"
        ".endm\n"
        ".macro DISPATCH reg\n"
        "    cmpl $0, %edx\n"
        "    je 5f\n"
        "    cmpl $1, %edx\n"
        "    je 6f\n"
        "    cmpl $2, %edx\n"
        "    je 7f\n"
        "    EXEC rcr, \\reg\n"
        "5:  EXEC rol, \\reg\n"
        "6:  EXEC ror, \\reg\n"
        "7:  EXEC rcl, \\reg\n"
        ".endm\n"
        "1:  DISPATCH %al\n"
        "2:  DISPATCH %ax\n"
        "3:  DISPATCH %eax\n"
#ifndef __i386__
        "4:  DISPATCH %rax\n"
#endif
        "START rt_rol_value\n"
        "    movl $0x80000001, %eax\n"
        "    roll $1, %eax\n"
        "    cmpl $3, %eax\n"
        "    RESULT sete\n"
        "START rt_ror_cf\n"
        "    movl $1, %eax\n"
        "    rorl $1, %eax\n"
        "    RESULT setb\n"
        "START rt_rcl_value\n"
        "    movl $0x80000000, %eax\n"
        "    stc\n"
        "    rcll $1, %eax\n"
        "    cmpl $1, %eax\n"
        "    RESULT sete\n"
        "START rt_rcr_value\n"
        "    movl $2, %eax\n"
        "    stc\n"
        "    rcrl $1, %eax\n"
        "    cmpl $0x80000001, %eax\n"
        "    RESULT sete\n"
        "START rt_rcl_unknown_carry_cf\n"
        "    movl $0x80000000, %eax\n"
        "    rcll $1, %eax\n"
        "    RESULT setb\n"
        "START rt_rcl_unknown_carry_of\n"
        "    movl $0x80000000, %eax\n"
        "    rcll $1, %eax\n"
        "    RESULT seto\n"
        "START rt_rcr_unknown_carry_cf\n"
        "    movl $1, %eax\n"
        "    rcrl $1, %eax\n"
        "    RESULT setb\n"
        "START rt_rcr_unknown_carry_of\n"
        "    movl $1, %eax\n"
        "    rcrl $1, %eax\n"
        "    RESULT seto\n"
        "START rt_unknown_operand\n"
        "    INPUT\n"
        "    movl %ecx, %eax\n"
        "    cmpl %ecx, %ecx\n"
        "    rorl $1, %eax\n"
        "    RESULT sete\n"
        "START rt_unknown_count\n"
        "    INPUT\n"
        "    movl $0x12345678, %eax\n"
        "    cmpl %ecx, %ecx\n"
        "    roll %cl, %eax\n"
        "    RESULT sete\n"
        "START rt_zero_count\n"
        "    INPUT\n"
        "    movl %ecx, %eax\n"
        "    stc\n"
        "    roll $32, %eax\n"
        "    RESULT setb\n"
        "START rt_cycle_count\n"
        "    movb $0x80, %al\n"
        "    stc\n"
        "    rolb $8, %al\n"
        "    RESULT setb\n"
        "START rt_carry_cycle\n"
        "    stc\n"
        "    rclb $9, %al\n"
        "    RESULT setb\n"
        "START rt_carry_cycle_of\n"
        "    movb $127, %al\n"
        "    addb $1, %al\n"
        "    rclb $9, %al\n"
        "    RESULT seto\n"
        "START rt_high_alias\n"
        "    movl $0x12348056, %eax\n"
        "    rorb $1, %ah\n"
        "    cmpl $0x12344056, %eax\n"
        "    RESULT sete\n"
        "START rt_count_alias\n"
        "    movl $9, %ecx\n"
        "    rolb %cl, %cl\n"
        "    cmpb $18, %cl\n"
        "    RESULT sete\n"
        "START rt_unknown_count_zero\n"
        "    INPUT\n"
        "    movl $0, %eax\n"
        "    roll %cl, %eax\n"
        "    cmpl $0, %eax\n"
        "    RESULT sete\n"
        ".macro SLOT\n"
#ifdef __i386__
        "    movl $rt_slot, %edx\n"
#else
        "    leaq rt_slot(%rip), %rdx\n"
#endif
        ".endm\n"
        "START rt_memory\n"
        "    SLOT\n"
#ifdef __i386__
        "    movl $0x80000001, (%edx)\n"
        "    roll $1, (%edx)\n"
        "    cmpl $3, (%edx)\n"
#else
        "    movl $0x80000001, (%rdx)\n"
        "    roll $1, (%rdx)\n"
        "    cmpl $3, (%rdx)\n"
#endif
        "    RESULT sete\n"
        "START rt_memory_initial\n"
        "    SLOT\n"
#ifdef __i386__
        "    roll $1, (%edx)\n"
        "    cmpl $3, (%edx)\n"
#else
        "    roll $1, (%rdx)\n"
        "    cmpl $3, (%rdx)\n"
#endif
        "    RESULT sete\n"
        "START rt_memory_ror\n"
        "    SLOT\n"
#ifdef __i386__
        "    movl $1, (%edx)\n"
        "    rorl $1, (%edx)\n"
        "    cmpl $0x80000000, (%edx)\n"
#else
        "    movl $1, (%rdx)\n"
        "    rorl $1, (%rdx)\n"
        "    cmpl $0x80000000, (%rdx)\n"
#endif
        "    RESULT sete\n"
        "START rt_memory_rcl\n"
        "    SLOT\n"
#ifdef __i386__
        "    movl $0x80000000, (%edx)\n"
        "    stc\n"
        "    rcll $1, (%edx)\n"
        "    cmpl $1, (%edx)\n"
#else
        "    movl $0x80000000, (%rdx)\n"
        "    stc\n"
        "    rcll $1, (%rdx)\n"
        "    cmpl $1, (%rdx)\n"
#endif
        "    RESULT sete\n"
        "START rt_memory_rcr\n"
        "    SLOT\n"
#ifdef __i386__
        "    movl $2, (%edx)\n"
        "    stc\n"
        "    rcrl $1, (%edx)\n"
        "    cmpl $0x80000001, (%edx)\n"
#else
        "    movl $2, (%rdx)\n"
        "    stc\n"
        "    rcrl $1, (%rdx)\n"
        "    cmpl $0x80000001, (%rdx)\n"
#endif
        "    RESULT sete\n"
        "START rt_undefined_of\n"
        "    movl $1, %eax\n"
        "    cmpl $1, %eax\n"
        "    roll $2, %eax\n"
        "    RESULT seto\n"
        "START rt_locked\n"
        "    stc\n"
        "    .byte 0xf0, 0xd1, 0xc0\n"
        "    RESULT setb\n"
        "START rt_target\n"
#ifdef __i386__
        "    movl $rt_destination, %ecx\n"
#else
        "    leaq rt_destination(%rip), %rcx\n"
#endif
        "    movl $1, %eax\n"
        "    rorl $1, %eax\n"
#ifdef __i386__
        "    pushl %ecx\n"
#else
        "    pushq %rcx\n"
#endif
        "    ret\n"
        "START rt_destination\n"
        "    movl $7, %eax\n"
        "    ret\n"
#ifndef __i386__
        "START rt_zero_upper\n"
        "    movq $-1, %rax\n"
        "    roll $32, %eax\n"
        "    movl $-1, %ecx\n"
        "    cmpq %rcx, %rax\n"
        "    RESULT sete\n"
#endif
        ".data\n"
        ".p2align 4\n"
        "rt_slot: .long 0x80000001\n"
#ifndef __APPLE__
        ".section .note.GNU-stack,\"\",@progbits\n"
#endif
);
